### ISSUE TITLE
brute analysis error

### ISSUE THREAD

**Issue by jychoi-hpc** [rkube/delta#19]
When I tried to run `analysis_brute.py` without thread, I got the following error:
```
ECEI file = adios_streaming018431/ECEI.018431.LFS.h5
Traceback (most recent call last):
  File "/Users/jyc/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/jyc/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jyc/anaconda3/lib/python3.7/site-packages/mpi4py/futures/__main__.py", line 72, in <module>
    main()
  File "/Users/jyc/anaconda3/lib/python3.7/site-packages/mpi4py/futures/__main__.py", line 60, in main
    run_command_line()
  File "/Users/jyc/anaconda3/lib/python3.7/site-packages/mpi4py/run.py", line 47, in run_command_line
    run_path(sys.argv[0], run_name='__main__')
  File "/Users/jyc/anaconda3/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/Users/jyc/anaconda3/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/jyc/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "receiver_brute.py", line 244, in <module>
    perform_analysis(channel_data, cfg, currentStep, trange)
  File "receiver_brute.py", line 133, in perform_analysis
    overlap=cfg['fft_params']['overlap'],detrend=cfg['fft_params']['detrend'],full=1,scipy=True)
TypeError: fftbins() got an unexpected keyword argument 'scipy'
```

It looks like the function defined in `fluctana` has no scipy signature:
```
    def fftbins(self, nfft, window, overlap, detrend, full=0):
```

**Comment by jychoi-hpc** [comment]
Simply removing that option, I was able to run. I will make a pull request later.
